#!/bin/sh

NAME="tcpreconciliation"
DESC="TCP reconciliation service"

# The path Jsvc
EXEC="/usr/bin/jsvc"

# The path to the folder containing the Java runtime
JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64"

# The path to the folder containing the kafka-streams-tcp-reconciliation-0.0.1.jar 
FILE_PATH="/home/vagrant/kafka-streams-tcp-reconciliation"

# Our classpath
CLASS_PATH="$FILE_PATH/target/kafka-streams-tcp-reconciliation-0.0.1-shaded.jar"

# The fully qualified name of the class to execute
CLASS="uk.ac.cam.cl.cadets.kafka.streams.reconciliation.TcpReconciliation"

# And command line arguments to be passed to the Java Daemon's init() method
ARGS=""

# The user to run the daemon as
USER="vagrant"

# The file that will contain out process identification number (pid)
PID="$FILE_PATH/$NAME.pid"

# System.out writes to this file
LOG_OUT="$FILE_PATH/$NAME.out"

# System.err writes to this file
LOG_ERR="$FILE_PATH/$NAME.err"

jsvc_exec()
{
    cd $FILE_PATH
    $EXEC -home $JAVA_HOME -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS $ARGS
}

case "$1" in
    start)
        echo "Starting $DESC"
        echo "$PID"

        # Start the service
        jsvc_exec

        echo "The $DESC has started."
    ;;
    stop)
        echo "Stopping the $DESC..."

        # Stop the service
        jsvc_exec "-stop"

        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then

            echo "Restarting the $DESC..."

            # Stop the service
            jsvc_exec "-stop"

            # Start the service
            jsvc_exec

            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac
